package com.mykaarma.kcommunications.utils;

public enum FilterName {

	INBOX, READY_FOR_FOLLOW_UP, FOLLOWED_UP_WITH, UNASSIGNED, NO_WELCOME_TEXT_SENT, 
	STOP_REQUESTED, UNRESPONDED, UNOPENED, DELAYED_MESSAGES, UNREAD_INTERNAL_NOTES, SENT,
	DELEGATED, NOTIFIER_DEFAULT, OPT_IN_REQUESTS, NOT_WAITING_FOR_RESPONSE, ALREADY_RESPONDED, WAITING_FOR_RESPONSE, MISSED_CALLS 
}