package com.mykaarma.kcommunications_model.enums;

public enum OptOutStatusUpdateEvent {
    
    STOP_MESSAGE_RECEIVED,
    STOP_SUSPECTED_MESSAGE_RECEIVED,
    OPTIN_MESSAGE_RECEIVED,
    GENERIC_MESSAGE_RECEIVED,
    USER_REQUESTED_SEND_OPTIN_REQUEST,
    USER_REQUESTED_OPT_OUT,
    COMMUNICATION_VALUE_CREATION,
    COMMUNICATION_STATUS_NOT_FOUND,
    DOUBLE_OPTIN_ROLLOUT,
    DOUBLE_OPTIN_ROLLBACK;
}
