package com.mykaarma.kcommunications_model.enums;

public enum VerificationFailureReason {

	INVALID_TWILIO_URL,
	INVALID_AWS_URL,
	INVALID_TWILIO_BYTES,
	INVALID_AWS_BYTES,
	AUDIO_URL_MISMATCH,
	BYTES_MISMATCH, 
	NO_RECORDING_URL, 
	AUDIO_EXISTS_ON_TWILIO,
	RECORDING_DELETED, 
	AUDIO_NOT_MIGRATED_TO_S3, 
	CALL_SID_DOES_NOT_EXIST,
	DURATION_MISMATCH,
	TEXT_SID_DOES_NOT_EXIST,
	MESSAGE_BODY_SIZE_MISMATCH
}
