package com.mykaarma.kcommunications_model.enums;

public enum WarningCode {
	DRAFT_ATTRIBUTES_PRESENT,
	MISSING_ATTACHMENT_DETAILS,
	INVALID_EMAIL,
	MISSING_DRAFT_FAILURE_REASONs,
	OPTED_OUT_COMMUNICATION_VALUE,
	FEATURE_NOT_ENABLED,
	CANT_OVERRIDE_OPTOUT,
	MISSING_DEALER_EMAIL,
	ATTACHMENTS_FAILED_TO_DELETE,
    NO_CUSTOMER_FOUND,
	UNAUTHORIZED_API_CALL_SOURCE,
	CANT_QUEUE_MESSAGE_IF_OPTED_OUT,
}
